# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-23 18:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dl', '0003_remove_userdata_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='email',
        ),
    ]
